### ISSUE TITLE
Naming of do notation macros

### ISSUE THREAD

**Issue by pyx** [pyx/hymn#6]
This has been bugging me for a while now.

When I wrote this a few years ago, I thought a single do notation macro was enough. Remember this was a spin off derived from my static site generator, in writing that I figured that most of the time, I used `(m-return ...)` like so:

```clojure
(defn add-theme-assets [documents]
  "add theme assets files"
  (do-monad
    [assets theme-assets]
    (m-return (chain assets documents))))

(setv get-themes
  (do-monad
    [available-themes get-available-themes
     theme-name (<- 'theme)]
    (m-return (list (get-theme-lineage theme-name available-themes)))))
```

This is how you do it in haskell, you use `return` to wrap the result into monad at the end unless the type of last expression is of a monad type, which is not most of the time.

After writing `(m-return)` time after time, I changed the macro to add `(m-return)` to the last form to save typing, so the above became:

```clojure
(defn add-theme-assets [documents]
  "add theme assets files"
  (do-monad
    [assets theme-assets]
    (chain assets documents)))

(setv get-themes
  (do-monad
    [available-themes get-available-themes
     theme-name (<- 'theme)]
    (list (get-theme-lineage theme-name available-themes))))
```

Occasionally, the last form will be a monadic action, that is, the type of the last expression is already a monad,  for example, the monad `theme-assets` being used above:

```clojure
(setv theme-assets
  (do-monad
    [themes get-themes
     ts (if-not themes
          (m-return [])
          (do-monad
            [css (make-stylesheet themes)]
            (->>
              themes
              (get-theme-settings 'assets)
              (map second)
              (remove none?)
              (map directory)
              chain.from-iterable
              (chain [css]))))]
    ts))
```

Notice that both branches of `if-not` return a monad, we have to extract the value in the binding form, then the extracted value (`ts`) is being wrapped again, then returned.  We could do better if we have another macro that do not add `(m-return)` to the last form, so I came up a macro, and without thinking, name it `(do-monad-m)`, the above thus became:
```clojure
(setv theme-assets
  (do-monad-m
    [themes get-themes]
    (if-not themes
      (m-return [])
      (do-monad
        [css (make-stylesheet themes)]
        (->>
          themes
          (get-theme-settings 'assets)
          (map second)
          (remove none?)
          (map directory)
          chain.from-iterable
          (chain [css]))))))
```

It looks better now, at least to my eyes.

But, every time I look back, I regret the naming of the macros, the reason being:

1. In hymn, post-fix `-m` indicates the type of the expression is a monad, while the default behaviour of `do-monad-m` is not, you have to add `m-return` yourself.
2. The `-m` does not even tell the truth, because both macros, when used correctly, should return a monad.
3. People come from haskell will be surprised that the most natural form of do notation `(do-monad)` does not work in the same way as in haskell, you don't have to use `(m-return)`, or if you do, you will have incorrect result.

So, I propose the rename of these macros, as:

- Rename `do-monad-m` to `do-monad`, this is what haskell users would expect.
- Rename `do-monad` to `do-monad-return`, this should make it clear that there is a `m-return` added automatically.

I know not that many people using this library, but I do not want to introduce breaking changes without input, so, would you please tell me your thoughts?

Thank you in advance and thank you for reading.

**Comment by pyx** [comment]
CC @MelomanCool , @tuturto , @zoek1 , thank you.

**Comment by tuturto** [comment]
Reasoning for the chance is solid and I personally wouldn't mind having to change my code when this is introduced.

**Comment by MelomanCool** [comment]
I'm all about the clear naming.

**Comment by pyx** [comment]
Nice, That's 3/4 :rofl: of our user base. Thanks. I will go for it.

**Comment by pyx** [comment]
Done on master.
